version: '3.8'

services:
  # Servicio para la aplicación PHP
  php:
    build: ./docker/php-fpm
    container_name: bolt_php_x
    volumes:
      - ./project:/var/www/html
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=bolt
      - DATABASE_USER=bolt
      - DATABASE_PASSWORD=secret
    depends_on:
      - db

  # Servicio para la base de datos MySQL
  db:
    image: mysql:5.7
    container_name: bolt_db_x
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bolt
      MYSQL_USER: bolt
      MYSQL_PASSWORD: secret

  # Servicio para Nginx
  webserver:
    image: nginx:latest
    container_name: bolt_webserver_x
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project/public:/var/www/html/public
    depends_on:
      - php
    ports:
      - "8080:80"

volumes:
  db_data:
